In [1]:
import numpy as np

To jest pierwszy **notebook** - <span style="color:red; font-size:16pt">Jupyter!</span><br>
Podstawy numpy

In [3]:
ar1 = np.array([5,2,5,27,7,435,78,4,33,33])
ar1

array([ 5, 2, 5, 27, 7, 435, 78, 4, 33, 33])

In [4]:
print(type(ar1))

<class 'numpy.ndarray'>


In [5]:
np.arange(17)

array([ 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16])

In [11]:
np.arange(22)+1

array([ 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17,
 18, 19, 20, 21, 22])

In [8]:
def myarange(lewa,prawa):
    return np.arange(lewa,prawa+1)

In [9]:
myarange(1,32)

array([ 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17,
 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32])

In [12]:
w = np.array([[1,2,3,4,6],
              [9,11,45,6,34],
              [74,2,0,24,7]])
w

array([[ 1, 2, 3, 4, 6],
 [ 9, 11, 45, 6, 34],
 [74, 2, 0, 24, 7]])

In [13]:
zw = [[1,2,3,4,6],
        [9,11,45,6,34],
        [74,2,0,24,7]]
zw

[[1, 2, 3, 4, 6], [9, 11, 45, 6, 34], [74, 2, 0, 24, 7]]

In [14]:
print(type(zw))
print(type(w))

<class 'list'>
<class 'numpy.ndarray'>


In [16]:
zw[0][1]

2

In [20]:
# zw[0,1]

In [17]:
w[0][1]

2

In [18]:
w[0,1]

2

In [21]:
#filtry
w[w<5]

array([1, 2, 3, 4, 2, 0])

In [22]:
pc = (w>=5)
w[pc]

array([ 6, 9, 11, 45, 6, 34, 74, 24, 7])

In [23]:
lg = (w%2==0)
w[lg]

array([ 2, 4, 6, 6, 34, 74, 2, 0, 24])

In [24]:
cv = w[(w>2)&(w<=21)]
cv

array([ 3, 4, 6, 9, 11, 6, 7])

In [25]:
l1 = [5,26,8]
l2 = [84,36,9]

lw = l1+l2
lw

[5, 26, 8, 84, 36, 9]

In [28]:
npl1 = np.array(l1)
npl2 = np.array(l2)
npw = npl1+npl2
npw

array([89, 62, 17])

In [34]:
con = np.concatenate((npl1,npl2))
con

array([ 5, 26, 8, 84, 36, 9])

In [36]:
dane = np.array([1,3,8])
one = np.ones(3,dtype=int)
third = np.arange(6,9)

In [37]:
dane+one

array([2, 4, 9])

In [38]:
dane-one

array([0, 2, 7])

In [39]:
dane*third

array([ 6, 21, 64])

In [40]:
dane/third

array([0.16666667, 0.42857143, 1. ])

In [41]:
dane*1.8753

array([ 1.8753, 5.6259, 15.0024])

In [43]:
m1 = np.array([[4,8,11],[67,101,3],[1,1,77]])
m2 = np.array([[499,9,3],[23,89,3],[2,4,11]])
wynik = (m1+m2)*m1

wynik

array([[ 2012, 136, 154],
 [ 6030, 19190, 18],
 [ 3, 5, 6776]])

In [44]:
print(f'wartosc minimum: {wynik.min()}')
print(f'wartosc maximum: {wynik.max()}')
print(f'wartosc średnia: {wynik.mean()}')
print(f'wartosc odchylenie standardowe: {wynik.std()}')

wartosc minimum: 3
wartosc maximum: 19190
wartosc średnia: 3813.777777777778
wartosc odchylenie standardowe: 5997.386296968183


In [45]:
#przekształcenie wektora w macierz
arr = np.arange(12).reshape(4,3)
arr

array([[ 0, 1, 2],
 [ 3, 4, 5],
 [ 6, 7, 8],
 [ 9, 10, 11]])

In [47]:
#tensor3D
t3d = np.arange(27).reshape((3,3,3))
t3d

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])